
services:
  desenrola_next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desenrola_next
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - desenrola_net

networks:
  desenrola_net:
    driver: bridge
