version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: desenrola_next
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
