FROM node:20-alpine

WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./
RUN npm install --include=dev

# Copiar código fonte
COPY . .

# Corrigir permissões
RUN mkdir -p /app/.next && chown -R node:node /app

USER node

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]
